# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
     - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
          version: 19.03.14
                              
      - checkout

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0

      - run:
          name: Run tests
          command: |
            docker-compose up -d
            
           


           
